const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("fs");
const os = require("os");
const path = require("path");
const { execFileSync } = require("child_process");

const { parsePendingBeliefReviewQueue } = require("../src/beliefs/review-queue-schema");

const REPO_ROOT = path.join(__dirname, "..");
const SCRIPT_PATH = path.join(REPO_ROOT, "scripts", "belief-extractor.js");

function writeFile(workspaceRoot, relativePath, content) {
  const fullPath = path.join(workspaceRoot, relativePath);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, content);
}

test("belief extractor writes deferred candidates through the shared review queue contract", (t) => {
  const workspaceRoot = fs.mkdtempSync(
    path.join(os.tmpdir(), "belief-extractor-queue-"),
  );
  t.after(() => fs.rmSync(workspaceRoot, { recursive: true, force: true }));

  writeFile(workspaceRoot, "AGENTS.md", "# AGENTS\n");
  writeFile(workspaceRoot, "beliefs/core.jsonl", "");
  writeFile(
    workspaceRoot,
    "memory/2026-03-18.md",
    `# 2026-03-18 — DEUS Activity Log

**Total activities:** 1

## Git Activity

## Commands Executed

## Decisions
- 2026-03-18 10:00:00 +07: Нужно CI.

## Interactions with Human

## System Events

---
*Auto-generated by DEUS memory manager*
`,
  );

  const stdout = execFileSync(process.execPath, [SCRIPT_PATH], {
    cwd: REPO_ROOT,
    env: {
      ...process.env,
      WORKSPACE: workspaceRoot,
    },
  }).toString();
  const result = JSON.parse(stdout.match(/\{[\s\S]*\}\s*$/)[0]);
  const pendingQueue = fs.readFileSync(
    path.join(workspaceRoot, "review", "pending-beliefs.md"),
    "utf8",
  );
  const [entry] = parsePendingBeliefReviewQueue(pendingQueue);

  assert.equal(result.deferred, 1);
  assert.equal(result.extracted, 0);
  assert.ok(entry.marker);
  assert.match(entry.marker, /^workflow-/);
  assert.doesNotMatch(entry.marker, /^2026-03-18-/);
  assert.equal(entry.promotion_decision, "review_before_promotion");
  assert.equal(entry.provenance, "memory_pattern");
  assert.deepEqual(entry.evidence_sources, ["memory/2026-03-18.md"]);
  assert.match(entry.notes, /signal via/);
  assert.match(entry.notes, /\[memory_pattern\]/);
});

test("belief extractor keeps sleep-reflection candidates on the review-first path", (t) => {
  const workspaceRoot = fs.mkdtempSync(
    path.join(os.tmpdir(), "belief-extractor-sleep-review-"),
  );
  t.after(() => fs.rmSync(workspaceRoot, { recursive: true, force: true }));

  writeFile(workspaceRoot, "AGENTS.md", "# AGENTS\n");
  writeFile(workspaceRoot, "beliefs/core.jsonl", "");
  writeFile(
    workspaceRoot,
    "memory/2026-03-18.md",
    `# 2026-03-18 — DEUS Activity Log

**Total activities:** 1

## System Events
- 2026-03-18 04:20:00 +07: Nightly consolidation: Нужно держать CI в фокусе.

---
*Auto-generated by DEUS memory manager*
`,
  );

  const stdout = execFileSync(process.execPath, [SCRIPT_PATH], {
    cwd: REPO_ROOT,
    env: {
      ...process.env,
      WORKSPACE: workspaceRoot,
    },
  }).toString();
  const result = JSON.parse(stdout.match(/\{[\s\S]*\}\s*$/)[0]);
  const pendingQueue = fs.readFileSync(
    path.join(workspaceRoot, "review", "pending-beliefs.md"),
    "utf8",
  );
  const [entry] = parsePendingBeliefReviewQueue(pendingQueue);

  assert.equal(result.extracted, 0);
  assert.equal(result.deferred, 1);
  assert.equal(entry.promotion_decision, "review_before_promotion");
  assert.equal(entry.provenance, "sleep_reflection");
  assert.match(entry.notes, /\[sleep_reflection\]/);
});
