const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const {
  createDeusWorkspaceFixtureSync,
} = require("./helpers/deus-workspace-fixture");
const { parsePendingBeliefReviewQueue } = require("../src/beliefs/review-queue-schema");

const REPO_ROOT = path.join(__dirname, "..");
const EXTRACTOR_PATH = path.join(REPO_ROOT, "scripts", "belief-extractor.js");
const PROMOTION_REVIEW_PATH = path.join(
  REPO_ROOT,
  "scripts",
  "belief-promotion-review.js",
);

function writeFile(workspaceRoot, relativePath, content) {
  const fullPath = path.join(workspaceRoot, relativePath);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, content);
}

function runScript(scriptPath, workspaceRoot) {
  const stdout = execFileSync(process.execPath, [scriptPath], {
    cwd: REPO_ROOT,
    env: {
      ...process.env,
      WORKSPACE: workspaceRoot,
    },
  }).toString();

  const match = stdout.match(/\{[\s\S]*\}\s*$/);
  if (!match) {
    throw new Error(`Missing JSON payload in stdout:\n${stdout}`);
  }

  return JSON.parse(match[0]);
}

test("belief pipeline preserves repeated extracted candidates through queue dedup and promotion review", (t) => {
  const workspaceRoot = createDeusWorkspaceFixtureSync();
  t.after(() => fs.rmSync(workspaceRoot, { recursive: true, force: true }));

  writeFile(
    workspaceRoot,
    "memory/2026-03-16.md",
    `# 2026-03-16 — DEUS Activity Log

**Total activities:** 1

## Decisions
- 2026-03-16 10:00:00 +07: Нужно CI.

## System Events

---
*Auto-generated by DEUS memory manager*
`,
  );
  writeFile(
    workspaceRoot,
    "memory/2026-03-17.md",
    `# 2026-03-17 — DEUS Activity Log

**Total activities:** 1

## Decisions
- 2026-03-17 10:00:00 +07: Нужно CI.

## System Events

---
*Auto-generated by DEUS memory manager*
`,
  );
  writeFile(
    workspaceRoot,
    "memory/2026-03-18.md",
    `# 2026-03-18 — DEUS Activity Log

**Total activities:** 1

## Decisions
- 2026-03-18 10:00:00 +07: Нужно CI.

## System Events

---
*Auto-generated by DEUS memory manager*
`,
  );

  const extractionResult = runScript(EXTRACTOR_PATH, workspaceRoot);
  assert.equal(extractionResult.extracted, 0);
  assert.equal(extractionResult.updated, 0);
  assert.equal(extractionResult.deferred, 3);

  const queueAfterExtraction = parsePendingBeliefReviewQueue(
    fs.readFileSync(
      path.join(workspaceRoot, "review", "pending-beliefs.md"),
      "utf8",
    ),
  );
  assert.equal(queueAfterExtraction.length, 1);
  assert.deepEqual(queueAfterExtraction[0], {
    header: queueAfterExtraction[0].header,
    marker: "workflow-user-requirement-нужно-ci",
    candidate: "User requirement: Нужно CI.",
    category: "workflow",
    evidence: "extracted from workflow pattern match",
    evidence_sources: [
      "memory/2026-03-16.md",
      "memory/2026-03-17.md",
      "memory/2026-03-18.md",
    ],
    recurrence: 3,
    confidence_proposal: 0.8,
    promotion_decision: "review_before_promotion",
    human_review_needed: "no",
    provenance: "memory_pattern",
    notes: 'strong signal via "Нужно CI." [memory_pattern]',
  });

  const promotionResult = runScript(PROMOTION_REVIEW_PATH, workspaceRoot);
  assert.equal(promotionResult.entries, 1);
  assert.equal(promotionResult.promoted, 1);
  assert.equal(promotionResult.deferred, 0);
  assert.equal(promotionResult.rejected, 0);

  const beliefs = fs
    .readFileSync(path.join(workspaceRoot, "beliefs", "core.jsonl"), "utf8")
    .trim()
    .split("\n")
    .filter(Boolean)
    .map((line) => JSON.parse(line));
  const promotedBelief = beliefs.find(
    (belief) => belief.content === "User requirement: Нужно CI.",
  );
  assert.ok(promotedBelief);
  assert.equal(promotedBelief.context_scope, "workflow");
  assert.deepEqual(promotedBelief.evidence_set, [
    "memory/2026-03-16.md",
    "memory/2026-03-17.md",
    "memory/2026-03-18.md",
  ]);

  const queueAfterPromotion = parsePendingBeliefReviewQueue(
    fs.readFileSync(
      path.join(workspaceRoot, "review", "pending-beliefs.md"),
      "utf8",
    ),
  );
  assert.equal(queueAfterPromotion.length, 1);
  assert.equal(queueAfterPromotion[0].promotion_decision, "promote");
  assert.equal(queueAfterPromotion[0].recurrence, 3);
});
