const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs/promises");
const os = require("node:os");
const path = require("node:path");

const {
  DAILY_MEMORY_SECTIONS,
  DAILY_MEMORY_TITLE_SUFFIX,
  DAILY_MEMORY_TOTAL_ACTIVITIES_LABEL,
} = require("../src/memory/daily-memory-schema");
const { DEUSMemoryFileStore } = require("../src/memory/deus-memory-file-store");
const { getHumanInteractionSectionTitle } = require("../src/memory/user-context");

function createDateContext() {
  return {
    today: "2026-03-18",
    localTimestamp: "2026-03-18 10:00:00 +07",
  };
}

test("validateFormat creates a canonical daily memory document from the shared schema", async () => {
  const workspace = await fs.mkdtemp(
    path.join(os.tmpdir(), "daily-memory-schema-valid-"),
  );
  const store = new DEUSMemoryFileStore({
    workspaceRoot: workspace,
    dateContextProvider: createDateContext,
  });

  const validation = await store.validateFormat();
  const content = await fs.readFile(store.memoryPath, "utf8");

  assert.equal(validation.valid, true);
  assert.match(
    content,
    new RegExp(`^# 2026-03-18 — ${DAILY_MEMORY_TITLE_SUFFIX}`, "m"),
  );
  assert.match(
    content,
    new RegExp(`\\*\\*${DAILY_MEMORY_TOTAL_ACTIVITIES_LABEL}:\\*\\* 0`),
  );

  for (const section of DAILY_MEMORY_SECTIONS) {
    assert.match(
      content,
      new RegExp(`## ${section.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\$&")}`),
    );
  }
});

test("validateFormat reports canonical section gaps with section-specific diagnostics", async () => {
  const workspace = await fs.mkdtemp(
    path.join(os.tmpdir(), "daily-memory-schema-invalid-"),
  );
  const store = new DEUSMemoryFileStore({
    workspaceRoot: workspace,
    dateContextProvider: createDateContext,
  });
  const memoryPath = path.join(workspace, "memory", "2026-03-18.md");

  await fs.mkdir(path.dirname(memoryPath), { recursive: true });
  await fs.writeFile(
    memoryPath,
    `# 2026-03-18 — ${DAILY_MEMORY_TITLE_SUFFIX}

**${DAILY_MEMORY_TOTAL_ACTIVITIES_LABEL}:** 1

## Git Activity
- 2026-03-18 09:00:00 +07: commit

## Decisions
- 2026-03-18 09:01:00 +07: keep going

---
*Auto-generated by DEUS memory manager*
`,
  );

  const validation = await store.validateFormat({
    createIfMissing: false,
  });

  assert.equal(validation.valid, false);
  assert.deepEqual(validation.missing, [
    "Commands Executed",
    getHumanInteractionSectionTitle({ workspaceRoot: workspace }),
    "System Events",
  ]);
});
