const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs/promises");
const os = require("node:os");
const path = require("node:path");

const { DEUSMemory } = require("../src/memory/deus-memory");
const { DAILY_MEMORY_SECTIONS } = require("../src/memory/daily-memory-schema");

function createMemory(workspace, currentContext) {
  return new DEUSMemory({
    workspaceRoot: workspace,
    dateContextProvider: () => currentContext,
  });
}

test("initToday and validateFormat normalize daily memory once without ordering drift", async () => {
  const workspace = await fs.mkdtemp(
    path.join(os.tmpdir(), "deus-memory-idempotency-"),
  );
  const currentContext = {
    today: "2026-03-18",
    localTimestamp: "2026-03-18 10:00:00 +07",
  };
  const memory = createMemory(workspace, currentContext);
  const brokenPath = path.join(workspace, "memory", "2026-03-18.md");

  await fs.mkdir(path.dirname(brokenPath), { recursive: true });
  await fs.writeFile(
    brokenPath,
    `# 2026-03-18 — DEUS Activity Log

**Total activities:** 9

## System Events
- 2026-03-18 09:00:00 +07: boot

## Git Activity
- 2026-03-18 09:01:00 +07: commit

---
*Auto-generated by DEUS memory manager*
`,
  );

  const created = await memory.initToday();
  const firstPass = await fs.readFile(brokenPath, "utf8");
  const validationA = await memory.validateFormat();
  const secondPass = await fs.readFile(brokenPath, "utf8");
  const validationB = await memory.validateFormat();
  const thirdPass = await fs.readFile(brokenPath, "utf8");

  assert.equal(created, false);
  assert.equal(validationA.valid, true);
  assert.equal(validationB.valid, true);
  assert.equal(firstPass, secondPass);
  assert.equal(secondPass, thirdPass);
  assert.match(firstPass, /\*\*Total activities:\*\* 2/);

  const sectionOrder = DAILY_MEMORY_SECTIONS.map((section) =>
    firstPass.indexOf(`## ${section}`),
  );

  assert.equal(
    sectionOrder.every((position) => position >= 0),
    true,
  );
  assert.equal(
    sectionOrder.every(
      (position, index) => index === 0 || position > sectionOrder[index - 1],
    ),
    true,
  );
  assert.equal(
    (firstPass.match(/^## /gm) || []).length,
    DAILY_MEMORY_SECTIONS.length,
  );
});

test("addEntry deduplicates repeated section writes with the same content", async () => {
  const workspace = await fs.mkdtemp(
    path.join(os.tmpdir(), "deus-memory-dedupe-"),
  );
  const currentContext = {
    today: "2026-03-18",
    localTimestamp: "2026-03-18 10:05:00 +07",
  };
  const memory = createMemory(workspace, currentContext);

  const firstAdd = await memory.logEvent("Repeated event");
  const secondAdd = await memory.logEvent("Repeated event");
  const content = await fs.readFile(memory.memoryPath, "utf8");

  assert.equal(firstAdd, true);
  assert.equal(secondAdd, false);
  assert.match(content, /\*\*Total activities:\*\* 1/);
  assert.equal(content.includes("Repeated event"), true);
  assert.equal((content.match(/Repeated event/g) || []).length, 1);
});
