const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs/promises");
const os = require("node:os");
const path = require("node:path");

const { DEUSMemory } = require("../src/memory/deus-memory");
const { DAILY_MEMORY_SECTIONS } = require("../src/memory/daily-memory-schema");
const { DEUSMemoryFileStore } = require("../src/memory/deus-memory-file-store");
const { OpenClawMemoryClient } = require("../src/openclaw/openclaw-memory-client");

function createDateContext() {
  return {
    today: "2026-03-18",
    localTimestamp: "2026-03-18 10:00:00 +07",
  };
}

test("fallbackSearch returns no results when the memory directory is absent", async () => {
  const workspace = await fs.mkdtemp(
    path.join(os.tmpdir(), "deus-memory-empty-search-"),
  );
  const store = new DEUSMemoryFileStore({
    workspaceRoot: workspace,
    dateContextProvider: createDateContext,
  });

  const results = await store.fallbackSearch("Git", 5);

  assert.deepEqual(results, []);
});

test("fallbackSearch handles literal special-character queries without regex drift", async () => {
  const workspace = await fs.mkdtemp(
    path.join(os.tmpdir(), "deus-memory-special-search-"),
  );
  const store = new DEUSMemoryFileStore({
    workspaceRoot: workspace,
    dateContextProvider: createDateContext,
  });
  const dayKey = createDateContext().today;
  const memoryPath = path.join(workspace, "memory", `${dayKey}.md`);

  await fs.mkdir(path.dirname(memoryPath), { recursive: true });
  await fs.writeFile(
    memoryPath,
    `# ${dayKey} — DEUS Activity Log

**Total activities:** 1

## Git Activity
- 2026-03-18 09:00:00 +07: tested [literal] C++ node.js (test)

## Commands Executed

## Decisions

## Interactions with Human

## System Events

---
*Auto-generated by DEUS memory manager*
`,
  );

  const results = await store.fallbackSearch("[literal] C++ node.js (test)", 5);

  assert.equal(results.length, 1);
  assert.equal(results[0].path, `memory/${dayKey}.md`);
  assert.equal(results[0].score, 1);
});

test("fallbackGet preserves missing-file failures for callers", async () => {
  const workspace = await fs.mkdtemp(
    path.join(os.tmpdir(), "deus-memory-missing-get-"),
  );
  const store = new DEUSMemoryFileStore({
    workspaceRoot: workspace,
    dateContextProvider: createDateContext,
  });

  await assert.rejects(store.fallbackGet("memory/missing.md"), /ENOENT/);
});

test("logEvent creates a canonical daily memory file in a fresh workspace", async () => {
  const workspace = await fs.mkdtemp(
    path.join(os.tmpdir(), "deus-memory-fresh-write-"),
  );
  const memory = new DEUSMemory({
    workspaceRoot: workspace,
    dateContextProvider: createDateContext,
  });

  const added = await memory.logEvent("Fresh workspace boot");
  const content = await fs.readFile(memory.memoryPath, "utf8");

  assert.equal(added, true);
  assert.match(content, /# 2026-03-18 — DEUS Activity Log/);
  for (const section of DAILY_MEMORY_SECTIONS) {
    assert.match(
      content,
      new RegExp(`## ${section.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\$&")}`),
    );
  }
  assert.match(content, /Fresh workspace boot/);
  assert.match(content, /\*\*Total activities:\*\* 1/);
});

test("OpenClawMemoryClient falls back when native tools are disabled or fail", async () => {
  const calls = [];
  const client = new OpenClawMemoryClient({
    memorySearchTool: async (payload) => {
      calls.push([
        "nativeSearch",
        payload.query,
        payload.maxResults,
        payload.minScore,
      ]);
      return { disabled: true };
    },
    memoryGetTool: async (payload) => {
      calls.push(["nativeGet", payload.path, payload.from, payload.lines]);
      throw new Error("native get unavailable");
    },
  });

  const searchResults = await client.search(
    "Git",
    { maxResults: 2, minScore: 0.5 },
    async (query, maxResults) => {
      calls.push(["fallbackSearch", query, maxResults]);
      return [{ path: "memory/example.md", score: 1 }];
    },
  );
  const getResult = await client.get(
    "memory/example.md",
    { from: 2, lines: 4 },
    async (filePath, from, lines) => {
      calls.push(["fallbackGet", filePath, from, lines]);
      return "fallback-content";
    },
  );

  assert.deepEqual(searchResults, [{ path: "memory/example.md", score: 1 }]);
  assert.equal(getResult, "fallback-content");
  assert.deepEqual(calls, [
    ["nativeSearch", "Git", 2, 0.5],
    ["fallbackSearch", "Git", 2],
    ["nativeGet", "memory/example.md", 2, 4],
    ["fallbackGet", "memory/example.md", 2, 4],
  ]);
});
