const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("fs");
const path = require("path");

const {
  createDeusWorkspaceFixtureSync,
} = require("./helpers/deus-workspace-fixture");
const { buildWorldModel } = require("../src/world-model/world-model-builder");

function writeFile(workspaceRoot, relativePath, content) {
  const fullPath = path.join(workspaceRoot, relativePath);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, content);
}

test("world-model builder derives a compact operational snapshot from current DEUS artifacts", (t) => {
  const workspaceRoot = createDeusWorkspaceFixtureSync();
  t.after(() => fs.rmSync(workspaceRoot, { recursive: true, force: true }));

  writeFile(
    workspaceRoot,
    "STATUS.md",
    "# STATUS.md\n\n## Current state\n- mode: working\n- active_project: deus\n- status: waiting\n- waiting_for: human confirmation\n- follow_through_required: yes\n\n## Open work block\n- goal: build world model\n- next_step: add builder\n- unblock_condition: confirmation\n",
  );
  writeFile(
    workspaceRoot,
    "memory/2026-03-21.md",
    "# 2026-03-21 - DEUS Activity Log\n\n## Git Activity\n\n## Commands Executed\n\n## Decisions\n\n## Interactions with Human\n\n## System Events\n\n---\n*Auto-generated by DEUS memory manager*\n",
  );
  writeFile(
    workspaceRoot,
    "PROJECTS.md",
    "# PROJECTS.md\n\n## Current Projects\n- deus\n",
  );
  writeFile(
    workspaceRoot,
    "review/pending-beliefs.md",
    "# Pending Belief Promotions\n\n## 2026-03-21T00:00:00Z - fixture\n- marker: shared-state-readers\n- candidate: Shared state readers now exist.\n",
  );
  writeFile(
    workspaceRoot,
    "review/open-tensions.md",
    "# Open Tensions\n\n## 2026-03-21T00:00:00Z - fixture\n- marker: missing-policy-hook\n- unresolved_issue: advisory evaluator surface is not wired yet.\n",
  );
  writeFile(
    workspaceRoot,
    "docs/introspection/introspection-summaries.jsonl",
    `${JSON.stringify({ date: "2026-03-20", coherence: 0.4 })}\n`,
  );

  const worldModel = buildWorldModel({
    workspaceRoot,
    now: "2026-03-21T02:00:00.000Z",
    runCommand() {
      return Buffer.from(" M src/example.js\u0000");
    },
  });

  assert.equal(worldModel.workspace_day, "2026-03-21");
  assert.equal(worldModel.self_model.invariants.length, 5);
  assert.equal(worldModel.workspace_model.active_project, "deus");
  assert.equal(worldModel.workspace_model.mode, "idle");
  assert.equal(worldModel.workspace_model.status, "waiting");
  assert.equal(worldModel.workspace_model.repo_dirty, true);
  assert.deepEqual(worldModel.environment_model.open_tensions, [
    "missing-policy-hook",
  ]);
  assert.deepEqual(worldModel.action_priors.hard_blocks, [
    "waiting_for_condition",
  ]);
  assert.equal(worldModel.sources.pending_beliefs.count, 1);
});
