import { CognitiveConfigService } from '../cognitive/cognitive-config.service';

// Returns default values for all config keys (same as the DEFAULTS in CognitiveConfigService)
const DEFAULTS: Record<string, number> = {
  'similarity.belief_match': 0.7,
  'similarity.contradiction_negation': 0.6,
  'similarity.contradiction_content': 0.5,
  'similarity.knowledge_match': 0.7,
  'similarity.cluster': 0.6,
  'similarity.memory_recall': 0.4,
  'decay.rate_slow': 0.001,
  'decay.rate_normal': 0.01,
  'decay.rate_fast': 0.02,
  'evidence.explicit_statement': 0.9,
  'evidence.strong_implication': 0.6,
  'evidence.behavioral_pattern': 0.4,
  'evidence.weak_inference': 0.2,
  'bayesian.learning_rate': 0.3,
  'bayesian.reinforcement_boost_cap': 0.1,
  'bayesian.ci_z_score': 1.645,
  'promotion.min_recurrence': 3,
  'promotion.min_confidence': 0.6,
  'promotion.defer_recurrence': 2,
  'promotion.confidence_boost': 0.03,
  'contradiction.confidence_penalty': 0.8,
  'contradiction.divergence_threshold': 0.5,
  'ripeness.w_goal_clarity': 0.22,
  'ripeness.w_world_quality': 0.20,
  'ripeness.w_dependency': 0.20,
  'ripeness.w_authorization': 0.18,
  'ripeness.w_environment': 0.12,
  'ripeness.w_freshness': 0.08,
  'ripeness.threshold_ready': 0.8,
  'ripeness.threshold_soon': 0.6,
  'introspection.coherence_w_avgconf': 0.6,
  'introspection.coherence_w_lowratio': 0.3,
  'introspection.coherence_penalty_per_contradiction': 0.05,
  'introspection.threshold_stable': 0.85,
  'introspection.threshold_review': 0.8,
  'introspection.low_confidence_threshold': 0.7,
  'worldmodel.stale_after_hours': 6,
  'worldmodel.memory_stale_days': 3,
  'importance.w_impact': 0.30,
  'importance.w_uniqueness': 0.20,
  'importance.w_relevance': 0.25,
  'importance.w_user_involvement': 0.15,
  'importance.w_belief_impact': 0.10,
  'context_decay.tools': 1.5,
  'context_decay.values': 0.3,
  'session.active_threshold_ms': 60000,
  'session.sporadic_threshold_ms': 300000,
  'session.high_load_length': 500,
  'session.medium_load_length': 100,
  'llm.max_tokens_recognition': 1024,
  'llm.max_tokens_extraction': 1024,
  'llm.max_tokens_deliberation': 1024,
};

export const mockCognitiveConfig: Partial<CognitiveConfigService> = {
  get: jest.fn((key: string) => DEFAULTS[key] ?? 0),
  set: jest.fn().mockResolvedValue({ isOk: () => true }),
  adjust: jest.fn().mockResolvedValue({ isOk: () => true }),
  getAll: jest.fn(() => []),
};
